#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

NORMAL='\033[0m'
BLUE='\033[0;34m'
IGREEN='\033[0;92m'
IRED='\033[0;91m'

echo -e "\n${BLUE}husky commit-msg hook을 실행합니다.${NORMAL}\n"

commitMessage=$(cat "$1")

# 현재 브랜치명 가져오기
branchName=$(git symbolic-ref --short HEAD)

# fe-feature 브랜치명 패턴 확인
if [[ $branchName =~ ^fe-feature- ]]; then
  domain=$(echo $branchName | sed -E 's/^fe-feature-//')
  commitRegex="^fe-feature\(${domain}\): \[.*\] .*"
else
  commitRegex="^(master|fe-master|fe-dev|fe-chore|fe-fix): .*"
fi

if ! [[ $commitMessage =~ $commitRegex ]]; then
  echo -e "${IRED}[ ERROR! ]: 커밋 메시지가 컨벤션을 준수하지 않았습니다. ${NORMAL}"
  if [[ $branchName =~ ^fe-feature- ]]; then
    echo -e "${IRED} - 'fe-(${domain}): [subfeature] 작업요약' 형식을 준수해야 합니다.${NORMAL}"
  else
    echo -e "${IRED} - 'master|fe-master, fe-dev, fe-chore, fe-fix: 작업요약' 형식을 준수해야 합니다.${NORMAL}"
  fi
  exit 1
fi
 
echo -e "\n${IGREEN}커밋 메시지가 컨벤션을 준수합니다.${NORMAL}\n"